// Code generated by tygo. DO NOT EDIT.

//////////
// source: entity.go

/**
 * Agent represents an AI persona.
 */
export interface Agent {
  agent_uuid: string;
  name: string;
  avatar?: string;
  description?: string;
  persona_prompt: string;
  model_config: ModelConfig;
  capabilities: Capabilities;
  created_at: string;
  updated_at: string;
}
/**
 * ModelConfig defines the specific LLM configuration for this agent.
 */
export interface ModelConfig {
  provider: string;
  model: string;
  temperature: number /* float64 */;
  top_p: number /* float64 */;
  max_tokens: number /* int */;
}
/**
 * Capabilities defines what this agent can do.
 */
export interface Capabilities {
  web_search: boolean;
  search_provider: string; // e.g., "tavily"
  code_execution: boolean;
}

//////////
// source: repository.go

/**
 * Repository defines the interface for agent persistence.
 */
export type Repository = any;
