// Code generated by tygo. DO NOT EDIT.

//////////
// source: entity.go

/**
 * Group represents a collaboration group (Project/Context).
 */
export interface Group {
  group_uuid: string;
  name: string;
  icon?: string;
  system_prompt?: string;
  default_agent_uuids: string[];
  created_at: string;
  updated_at: string;
}

//////////
// source: repository.go

/**
 * Repository defines the interface for group persistence.
 */
export type Repository = any;
