// Code generated by tygo. DO NOT EDIT.

//////////
// source: context.go

/**
 * StreamEvent represents a real-time event sent to the client
 */
export interface StreamEvent {
  event: string; // e.g. "token_stream", "node_state_change", "error"
  timestamp: string;
  node_id?: string;
  data?: { [key: string]: any};
}
/**
 * WorkflowContext handles state and data flow during execution
 */
export interface WorkflowContext {
  SessionID: string;
}

//////////
// source: cost.go

export interface CostEstimate {
  total_cost_usd: number /* float64 */;
  total_tokens: number /* int */;
  node_breakdown: { [key: string]: NodeCostEstimate};
  agent_breakdown: { [key: string]: number /* float64 */};
}
export interface NodeCostEstimate {
  cost_usd: number /* float64 */;
  tokens: number /* int */;
}

//////////
// source: engine.go

/**
 * Engine orchestrates the workflow execution
 */
export interface Engine {
  Graph?: GraphDefinition;
  Status: { [key: string]: NodeStatus};
  NodeFactory: any;
  StreamChannel: any;
  /**
   * Middleware hooks
   */
  Middlewares: Middleware[];
  Session?: Session; // Reference to the session state
}

//////////
// source: processor.go

/**
 * NodeProcessor defines the interface that all node types must implement
 */
export type NodeProcessor = any;

//////////
// source: repository.go

/**
 * WorkflowEntity represents the persistent storage for a workflow.
 */
export interface WorkflowEntity {
  workflow_uuid: string;
  group_uuid: string;
  name: string;
  graph_definition: GraphDefinition;
  created_at: string;
  updated_at: string;
}
/**
 * Repository defines the interface for workflow persistence.
 */
export type Repository = any;

//////////
// source: session.go

export type SessionStatus = string;
export const SessionPending: SessionStatus = "pending";
export const SessionRunning: SessionStatus = "running";
export const SessionPaused: SessionStatus = "paused";
export const SessionCompleted: SessionStatus = "completed";
export const SessionFailed: SessionStatus = "failed";
export const SessionCancelled: SessionStatus = "cancelled";
/**
 * Session represents a single execution instance of a workflow
 */
export interface Session {
  session_uuid: string;
  Graph?: GraphDefinition;
  Status: SessionStatus;
  StartTime: string;
  EndTime: string;
  Inputs: { [key: string]: any};
  Outputs: { [key: string]: any};
  Error: any;
  SignalChannels: { [key: string]: any};
}

//////////
// source: session_repository.go

/**
 * SessionEntity represents the persistent state of a session.
 */
export interface SessionEntity {
  session_uuid: string;
  group_uuid: string;
  workflow_uuid: string;
  status: SessionStatus;
  proposal: { [key: string]: any};
  started_at?: any; // Simplified for now
  ended_at?: any;
}
/**
 * SessionRepository defines the interface for session persistence.
 */
export type SessionRepository = any;

//////////
// source: template.go

export type TemplateCategory = string;
export const TemplateCategoryCodeReview: TemplateCategory = "code_review";
export const TemplateCategoryBusinessPlan: TemplateCategory = "business_plan";
export const TemplateCategoryQuickDecision: TemplateCategory = "quick_decision";
export const TemplateCategoryCustom: TemplateCategory = "custom";
export const TemplateCategoryOther: TemplateCategory = "other";
export interface Template {
  template_uuid: string;
  name: string;
  description: string;
  category: TemplateCategory;
  is_system: boolean;
  graph: GraphDefinition;
  created_at: string;
  updated_at: string;
}
export type TemplateRepository = any;

//////////
// source: types.go

/**
 * NodeStatus defines the execution state of a node
 */
export type NodeStatus = string;
export const StatusPending: NodeStatus = "pending";
export const StatusRunning: NodeStatus = "running";
export const StatusCompleted: NodeStatus = "completed";
export const StatusFailed: NodeStatus = "failed";
export const StatusSkipped: NodeStatus = "skipped";
export const StatusSuspended: NodeStatus = "suspended";
/**
 * NodeType enum for supported node types
 */
export type NodeType = string;
export const NodeTypeStart: NodeType = "start";
export const NodeTypeEnd: NodeType = "end";
export const NodeTypeAgent: NodeType = "agent";
export const NodeTypeLLM: NodeType = "llm"; // Direct LLM call
export const NodeTypeTool: NodeType = "tool"; // Search, etc.
export const NodeTypeParallel: NodeType = "parallel"; // Logic node: Parallel branch
export const NodeTypeSequence: NodeType = "sequence"; // Logic node: Sequential steps
export const NodeTypeVote: NodeType = "vote"; // Logic node: Vote
export const NodeTypeLoop: NodeType = "loop"; // Logic node: Loop
export const NodeTypeFactCheck: NodeType = "fact_check"; // Logic node: Fact Check
export const NodeTypeHumanReview: NodeType = "human_review"; // Logic node: Human Review
export const NodeTypeMemoryRetrieval: NodeType = "memory_retrieval"; // Logic node: Memory Retrieval
/**
 * GraphDefinition represents the static definition of a workflow
 */
export interface GraphDefinition {
  workflow_id: string;
  name: string;
  description: string;
  nodes: { [key: string]: Node | undefined};
  start_node_id: string;
}
/**
 * Node represents a single step in the workflow
 */
export interface Node {
  node_id: string;
  type: NodeType;
  name: string;
  next_ids?: string[]; // Adjacency list for next steps
  properties: { [key: string]: any}; // Node-specific config (e.g. Prompt, Model)
}
/**
 * Middleware allows intercepting node execution for safety and observability
 */
export type Middleware = any;
